// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwh7dgvDiLMXQ6K2n9ugL4HBaBIu1iktY',
    appId: '1:586152874137:web:5a72a48b7202bae229e808',
    messagingSenderId: '586152874137',
    projectId: 'album-hanasana',
    authDomain: 'album-hanasana.firebaseapp.com',
    storageBucket: 'album-hanasana.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCet-mxQPE0LQaHXGBn4_3Yym7jDVq7Zvc',
    appId: '1:586152874137:android:f81593c2121e0c8e29e808',
    messagingSenderId: '586152874137',
    projectId: 'album-hanasana',
    storageBucket: 'album-hanasana.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4veu__O5IenUvfFinmy2hCK-mvmBwOhM',
    appId: '1:586152874137:ios:d45f56780c17b4f429e808',
    messagingSenderId: '586152874137',
    projectId: 'album-hanasana',
    storageBucket: 'album-hanasana.appspot.com',
    iosClientId: '586152874137-tq5sucnukd4a1dba52e7q9r2dbdbd1te.apps.googleusercontent.com',
    iosBundleId: 'com.hs.album',
  );
}
